#include <stdio.h>
#include <string.h>
#include <dot.h>


int main () {
	DOT_PARSER *dotParser = dot_parser_new ();

	char *line001 = "version:1\n";
	char *line002 = "author:Anoop Kumar Narayanan\n";
	char *line003 = " \r\n";
	char *line004 = "	\n";
	char *line005 = " 						\n";
	char *line006 = "\n";
	char *line007 = "\r\n";
	char *line008 = ".html first:1first second:2second        third:3third\n";
	char *line009 = ".html1 @:xyz123 first:1first  first:2first first:3first first:4first   second:2second        third:3third\n";
	char *line010 = ".html2 @:xyz1234 first:1first    second:2second        third:3third fourth:4fourth12345_this_will_do fifth: sixth: seventh: eighth:8th\n";
	char *line011 = ".html3 .:xyz1234 first:1first    xxxsecond:2second  \n";
	char *line012 = "..html3.1 .:xyz1234 #:one,two,three,four first:1first    xxxsecond:2second  \n";
	char *line013 = "....html3.2 .:xyz1234 first:1first    xxxsecond:2second  \n";
	char *line014 = "...html4.1 @:delAll .:xyz1234 #:one,two,three first:1first first:new1   first:new2   first:new3      first:new4   xxxsecond:2second  \n";
	char *line015 = "....+ third:3third fourth:4fourth fifth:5fifth  \n";
	char *line016 = "....+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line017 = ".....+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line018 = "...+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line019 = "...html4.2 .:xyz1234 #:one,two,three, first:1first    xxxsecond:2second  \n";
	char *line020 = "...html4.3 .:xyz1234 #:one,two,three first:1first    xxxsecond:2second  \n";
	char *line021 = "...html5.0 .:xyz1234````n_anoop_kumar`r`n`t`z`@ #:one,two,three first:1first    xxxsecond:2second  \n";
	char *line022 = "..html4.0 kkkk:xyz1234```n_anoop_kumar`r`n`t`z`@ #:one`,two,three first:1first    xxxsecond:2second  \n";
	char *line023 = ".html5.1 kkkk:xyz1234```n_anoop_kumar`r`n`t`z`@` #:one`,two,three first:1first    xxxsecond:2second  \n";
	char *line024 = ".html6.1 kkkk`:`:`:`:`::xyz1234```n_anoop_kumar`r`n`t`z`@` #:one`,two,three first:1first    xxxsecond:2second  \n";
	char *line025 = ".html7.1 #:one,two,three`,four` five\n";
	char *line026 = ".html8 .:xyz1234 first:1first    xxxsecond:2second  \n";
	char *line027 = "..html8.1 .:xyz1234 #:one,two,three,four first:1first    xxxsecond:2second  \n";
	char *line028 = "...html8.2 .:xyz1234 first:1first    xxxsecond:2second  \n";
	char *line029 = "...html8.3 .:xyz1234 #:one,two,three first:1first    xxxsecond:2second  \n";
	char *line030 = "....html8.4 .:xyz1234 first:1first    xxxsecond:2second  \n";
	char *line031 = ".html1 @:xyz123 #:a1,b2,c3 .:xyz1234 first:1first    xxxsecond:2second  \n";
	char *line031a = "..+ third:3third fourth:4fourth fifth:5fifth  \n";
	char *line031b = "..+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line031c = ".^ \n";
	char *line032 = ".html9 @:1234567 #:d4,e5,f6 .:xyz5678 first:2first    xxxsecond:3second  \n";
	char *line033 = ".html10 @:1234 #:d4,e5,f6 .:xyz5678 first:2first    xxxsecond:3second  \n";
	char *line034 = "..body10 @:123xxx4 #:d4,e5,f6 .:xyz5678 first:2first    xxxsecond:3second  \n";
	char *line035 = "..body10 #:rtd4,re5,wf6 .:xyz5678 first:2first    xxxsecond:3second  @:123xxx4 \n";
	char *line035a = ".^ \n";
	char *line036 = ".html5.1 kkkk:xyz1234```n_anoop_kumar`r`n`t`z`@` #:one`,two,three first:1first    xxxsecond:2second` to` none  \n";
	char *line037 = ".html6.1 kkkk`:`:`:`:`::xyz1234```n_anoop_kumar`r`n`t`z`@` #:one`,two,three first:1first    xxxsecond:2second  \n";
	char *line038 = ".html7.1 #:one,two,three`,four` five result:`$anoop$$$ result2:_$value result3:`_$value2\n";
	char *line039 = "..+ third:3third fourth:4fourth fifth:5fifth  \n";
	char *line040 = "..+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line041 = ".....+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line042 = "...+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line043 = ".+ 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line044 = "..Xyz #:anoop,kumar`,narayanan 1third:3third 2fourth:4fourth 4fifth:5fifth  \n";
	char *line045 = "@ 1234\n";
	char *line046 = "@ xyz123\n";
	char *line047 = "@     \n";
	char *line048 = "@     \r\n";
	char *line049 = "@          1234\n";
	char *line050 = "@             xyz123\n";
	char *line051 = "#  +:first,0,first,0\n";
	char *line052 = "#  -:first,0\n";
	char *line053 = "#  -:first,2\n";
	char *line054 = "#  -:first,0\n";
	char *line055 = "#  -:first,0\n";
	char *line056 = "#  -:.,0\n";
	char *line057 = "#  -:#,0\n";
	char *line058 = "@             delAll\n";
	char *line059 = "#  -:first\n"; //Remove all attributes with name first
	


	char buf[65536];
//#if 0
	strcpy( buf, line001);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line002);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line003);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line004);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line005);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line006);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line007);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line008);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line009);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line010);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line011);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line012);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line013);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line014);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line015);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line016);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line017);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line018);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line019);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line020);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line021);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
//#endif
	strcpy( buf, line022);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line023);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line024);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line025);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );

	strcpy( buf, line026);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line027);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line028);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line029);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line030);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line031);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line031a);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line031b);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line031c);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line032);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line033);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line034);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line035);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line035a);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line036);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line037);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line038);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );

	strcpy( buf, line039);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line040);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line041);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line042);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line043);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line044);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line045);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line046);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line047);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line048);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line049);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line050);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line051);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line052);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line053);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line054);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line055);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line056);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line057);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line058);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );
	strcpy( buf, line059);
	dot_parser_parse_line ( dotParser, buf, strlen(buf) );

	fprintf(stderr,"INFO: main(): ======================================================\n");
	dot_parser_dump( dotParser->docRoot, 0 );

	dot_parser_delete( dotParser );
	//fprintf(stderr,"INFO: main(): ======================================================\n");
	//dot_parser_dump( dotParser->docRoot, 0 );
	return 0;
}
